function y = doDifferentiate(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.5 and DSP System Toolbox 9.7.
% Generated on: 24-Mar-2019 15:47:39

persistent Hd;

if isempty(Hd)
    
    Fpass = 14000000;  % Passband Frequency
    Fstop = 20000000;  % Stopband Frequency
    Apass = 1;         % Passband Ripple (dB)
    Astop = 60;        % Stopband Attenuation (dB)
    Fs    = 48000000;  % Sampling Frequency
    
    h = fdesign.differentiator('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, ...
        Fs);
    
    Hd = design(h, 'equiripple');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

